---
namespace: ingress-nginx

helmCharts:
  - name: ingress-nginx
    releaseName: ingress
    version: 4.3.0
    repo: https://kubernetes.github.io/ingress-nginx
    valuesFile: values.yaml

configurations:
  - var_references.yaml

configMapGenerator:
- name: argocd-plant
  envs: [environment-properties.env]
  behavior: create

vars:
  - name: INGRESS_IP_ADDRESS
    objref:
      kind: ConfigMap
      name: argocd-plant
      apiVersion: v1
    fieldref:
      fieldpath: data.INGRESS_IP_ADDRESS
  - name: INGRESS_RESOURCE_GROUP
    objref:
      kind: ConfigMap
      name: argocd-plant
      apiVersion: v1
    fieldref:
      fieldpath: data.INGRESS_RESOURCE_GROUP
