---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-secret
spec:
  secretStoreRef:
    name: azure-store
    kind: SecretStore
  refreshInterval: "1m"
  target:
    name: test-secret
  data:
    - secretKey: testkey
      remoteRef:
        key: secret1
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
    - image: busybox
      command:
        - sleep
        - "3600"
      name: busybox
      volumeMounts:
        - name: external-secret
          mountPath: /var/secrets
          readOnly: true
  volumes:
    - name: external-secret
      secret:
        secretName: test-secret
        items:
          - key: testkey
            path: kvsecret
